#include "enum/VMCommands.hpp"

std::map<OperationType, std::string> operation_to_string{
        {OperationType::FETCHNEW,     "FETCHNEW"},
        {OperationType::FETCH,        "FETCH"},
        {OperationType::FETCHARR,     "FETCHARR"},
        {OperationType::FETCHARRFILL, "FETCHARRFILL"},
        {OperationType::FETCHELEMENT, "FETCHELEMENT"},
        {OperationType::UNFETCH,      "UNFETCH"},
        {OperationType::STORE,        "STORE"},
        {OperationType::PUSH,         "PUSH"},
        {OperationType::POP,          "POP"},
        {OperationType::ADD,          "ADD"},
        {OperationType::SUB,          "SUB"},
        {OperationType::MULTI,        "MULTI"},
        {OperationType::DIV,          "DIV"},
        {OperationType::MOD,          "MOD"},
        {OperationType::LT,           "LT"},
        {OperationType::BT,           "BT"},
        {OperationType::EQUAL,        "EQUAL"},
        {OperationType::NONEQUAL,     "NONEQUAL"},
        {OperationType::PRINT,        "PRINT"},
        {OperationType::PRINTLN,      "PRINTLN"},
        {OperationType::READ,         "READ"},
        {OperationType::JZ,           "JZ"},
        {OperationType::JNZ,          "JNZ"},
        {OperationType::GOTO,         "GOTO"},
        {OperationType::HALT,         "HALT"}
};

std::map<std::string, OperationType> string_to_operation{
        {"FETCHNEW",     OperationType::FETCHNEW},
        {"FETCH",        OperationType::FETCH},
        {"FETCHARR",     OperationType::FETCHARR},
        {"FETCHARRFILL", OperationType::FETCHARRFILL},
        {"FETCHELEMENT", OperationType::FETCHELEMENT},
        {"UNFETCH",      OperationType::UNFETCH},
        {"STORE",        OperationType::STORE},
        {"PUSH",         OperationType::PUSH},
        {"POP",          OperationType::POP},
        {"ADD",          OperationType::ADD},
        {"SUB",          OperationType::SUB},
        {"MULTI",        OperationType::MULTI},
        {"DIV",          OperationType::DIV},
        {"MOD",          OperationType::MOD},
        {"LT",           OperationType::LT},
        {"BT",           OperationType::BT},
        {"EQUAL",        OperationType::EQUAL},
        {"NONEQUAL",     OperationType::NONEQUAL},
        {"PRINT",        OperationType::PRINT},
        {"PRINTLN",      OperationType::PRINTLN},
        {"READ",         OperationType::READ},
        {"JZ",           OperationType::JZ},
        {"JNZ",          OperationType::JNZ},
        {"GOTO",         OperationType::GOTO},
        {"HALT",         OperationType::HALT}
};