#include "enum/VMCommands.hpp"

std::map<OperationType, std::string> operationNames{
        {OperationType::FETCHNEW, "FETCHNEW"},
        {OperationType::FETCH, "FETCH"},
        {OperationType::FETCHARR, "FETCHARR"},
        {OperationType::FETCHELEMENT, "FETCHELEMENT"},
        {OperationType::UNFETCH, "UNFETCH"},
        {OperationType::STORE, "STORE"},
        {OperationType::PUSH, "PUSH"},
        {OperationType::POP, "POP"},
        {OperationType::ADD, "ADD"},
        {OperationType::SUB, "SUB"},
        {OperationType::MULTI, "MULTI"},
        {OperationType::DIV, "DIV"},
        {OperationType::LT, "LT"},
        {OperationType::BT, "BT"},
        {OperationType::EQUAL, "EQUAL"},
        {OperationType::NONEQUAL, "NONEQUAL"},
        {OperationType::PRINT, "PRINT"},
        {OperationType::READ, "READ"},
        {OperationType::JZ, "JZ"},
        {OperationType::JNZ, "JNZ"},
        {OperationType::JMP, "JMP"},
        {OperationType::HALT, "HALT"}
};

std::map<std::string, OperationType> operationNamesStr{
        {"FETCHNEW", OperationType::FETCHNEW},
        {"FETCH", OperationType::FETCH},
        {"FETCHARR", OperationType::FETCHARR},
        {"FETCHELEMENT", OperationType::FETCHELEMENT},
        {"UNFETCH", OperationType::UNFETCH},
        { "STORE",OperationType::STORE},
        { "PUSH",OperationType::PUSH},
        { "POP",OperationType::POP},
        { "ADD",OperationType::ADD},
        { "SUB",OperationType::SUB},
        { "MULTI",OperationType::MULTI},
        { "DIV",OperationType::DIV},
        {"LT",OperationType::LT },
        {"BT",OperationType::BT },
        { "EQUAL",OperationType::EQUAL},
        { "NONEQUAL",OperationType::NONEQUAL},
        {"PRINT", OperationType::PRINT},
        {"READ", OperationType::READ},
        { "JZ",OperationType::JZ},
        { "JNZ",OperationType::JNZ},
        { "JMP",OperationType::JMP},
        { "HALT",OperationType::HALT}
};